name: CI-release-on-new-tag
on:
  push:
    branches: [main]
    tags: 
      - '*'
  pull_request:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-47
      options: --privileged
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - uses: flatpak/flatpak-github-actions/flatpak-builder@v6.3
      with:
        bundle: deadbeef.flatpak
        manifest-path: music.deadbeef.player-master.json
        cache-key: flatpak-builder-${{ github.sha }}
    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: deadbeef.flatpak

